source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'YLBNetworking_Example' do
  pod 'YLBNetworking', :path => '../'

  target 'YLBNetworking_Tests' do
    inherit! :search_paths

    
  end
end
